/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.testing.api;


@javax.annotation.processing.Generated(value = ["Autogenerated by Thrift Compiler (0.15.0)"], date = "2021-05-29")
public enum class ErrorCodes(
  override val value: Int
): org.apache.thrift.TEnum {
  AUTH_ERROR(0),
  SERVER_ERROR(1),
  INVALID_CODE(2),
  UNKNOWN_ERROR(1280),
  DECIMAL(100);

  companion object {
    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    fun findByValue(value: Int): ErrorCodes? {
      return when (value) {
        0 -> 
          AUTH_ERROR
        1 -> 
          SERVER_ERROR
        2 -> 
          INVALID_CODE
        1280 -> 
          UNKNOWN_ERROR
        100 -> 
          DECIMAL
        else ->
          null
      }
    }
  }
}
