/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.testing.api;

@javax.annotation.processing.Generated(value = ["Autogenerated by Thrift Compiler (0.15.0)"], date = "2021-05-29")
public class HelloAll( 
  private var Variable1: String?  = null, // required
  private var Variable2: Int = 0, // required
  private var Variable3: Long = 0, // required
  private var ChildNode: ChildAll?  = ChildAll() // required
): org.apache.thrift.TBase<HelloAll, HelloAll._Fields>, java.io.Serializable, Cloneable, Comparable<HelloAll> {

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum class _Fields(
    override val thriftFieldId: Short,
    override val fieldName: String
  ) : org.apache.thrift.TFieldIdEnum {
    VARIABLE1(1, "Variable1"),
    VARIABLE2(2, "Variable2"),
    VARIABLE3(3, "Variable3"),
    CHILD_NODE(4, "ChildNode");

    companion object {
      var byName: Map<String, _Fields> = mapOf(
        "Variable1" to VARIABLE1,
        "Variable2" to VARIABLE2,
        "Variable3" to VARIABLE3,
        "ChildNode" to CHILD_NODE
      )
      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      fun findByThriftId(fieldId: Int): _Fields? {
        return when(fieldId) {
          1 -> // VARIABLE1
            VARIABLE1
          2 -> // VARIABLE2
            VARIABLE2
          3 -> // VARIABLE3
            VARIABLE3
          4 -> // CHILD_NODE
            CHILD_NODE
          else ->
            null
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      fun findByThriftIdOrThrow(fieldId: Int): _Fields {
        return findByThriftId(fieldId)
          ?: throw java.lang.IllegalArgumentException("Field $fieldId doesn't exist!");
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      fun findByName(name: String): _Fields? {
        return byName.get(name)
      }
    }
  }

  private var  __isset_bitfield: Byte = 0
  /**
   * Performs a deep copy on <i>other</i>.
   */
  constructor(other: HelloAll) : this() {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetVariable1()) {
      this.Variable1 = other.Variable1
    }
    this.Variable2 = other.Variable2
    this.Variable3 = other.Variable3
    if (other.isSetChildNode()) {
      this.ChildNode = ChildAll(other.ChildNode!!)
    }
  }

  override fun deepCopy(): HelloAll{
    return HelloAll(this)
  }

  override fun clear() {
    this.Variable1 = null
    setVariable2IsSet(false);
    this.Variable2 = 0;
    setVariable3IsSet(false);
    this.Variable3 = 0;
    this.ChildNode?.clear()
  }

  fun getVariable1():String? {
    return this.Variable1
  }

  fun setVariable1(Variable1: String?): HelloAll {
    this.Variable1 = Variable1
    return this
  }

  fun unsetVariable1() {
    this.Variable1 = null;
  }

  /** Returns true if field Variable1 is set (has been assigned a value) and false otherwise */
  fun isSetVariable1(): Boolean {
    return this.Variable1 != null;
  }

  fun setVariable1IsSet(value: Boolean) {
    if (!value) {
      this.Variable1 = null;
    }
  }

  fun getVariable2():Int {
    return this.Variable2
  }

  fun setVariable2(Variable2: Int): HelloAll {
    this.Variable2 = Variable2
    setVariable2IsSet(true);
    return this
  }

  fun unsetVariable2() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VARIABLE2_ISSET_ID);
  }

  /** Returns true if field Variable2 is set (has been assigned a value) and false otherwise */
  fun isSetVariable2(): Boolean {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VARIABLE2_ISSET_ID);
  }

  fun setVariable2IsSet(value: Boolean) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VARIABLE2_ISSET_ID, value);
  }

  fun getVariable3():Long {
    return this.Variable3
  }

  fun setVariable3(Variable3: Long): HelloAll {
    this.Variable3 = Variable3
    setVariable3IsSet(true);
    return this
  }

  fun unsetVariable3() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VARIABLE3_ISSET_ID);
  }

  /** Returns true if field Variable3 is set (has been assigned a value) and false otherwise */
  fun isSetVariable3(): Boolean {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VARIABLE3_ISSET_ID);
  }

  fun setVariable3IsSet(value: Boolean) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VARIABLE3_ISSET_ID, value);
  }

  fun getChildNode():ChildAll? {
    return this.ChildNode
  }

  fun setChildNode(ChildNode: ChildAll?): HelloAll {
    this.ChildNode = ChildNode
    return this
  }

  fun unsetChildNode() {
    this.ChildNode = null;
  }

  /** Returns true if field ChildNode is set (has been assigned a value) and false otherwise */
  fun isSetChildNode(): Boolean {
    return this.ChildNode != null;
  }

  fun setChildNodeIsSet(value: Boolean) {
    if (!value) {
      this.ChildNode = null;
    }
  }

  override fun setFieldValue(field: _Fields,  value: Any?) {
    when (field) {
    _Fields.VARIABLE1 ->
      if (value == null) {
        unsetVariable1();
      } else {
        setVariable1(value as String);
      }

    _Fields.VARIABLE2 ->
      if (value == null) {
        unsetVariable2();
      } else {
        setVariable2(value as Int);
      }

    _Fields.VARIABLE3 ->
      if (value == null) {
        unsetVariable3();
      } else {
        setVariable3(value as Long);
      }

    _Fields.CHILD_NODE ->
      if (value == null) {
        unsetChildNode();
      } else {
        setChildNode(value as ChildAll);
      }

    }
  }

  override fun getFieldValue(field: _Fields): Any? {
    return when(field) {
      _Fields.VARIABLE1 -> getVariable1()
      _Fields.VARIABLE2 -> getVariable2()
      _Fields.VARIABLE3 -> getVariable3()
      _Fields.CHILD_NODE -> getChildNode()
    }
  }

  // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
  override fun isSet(field: _Fields): Boolean {
    return when (field) {
      _Fields.VARIABLE1->isSetVariable1()
      _Fields.VARIABLE2->isSetVariable2()
      _Fields.VARIABLE3->isSetVariable3()
      _Fields.CHILD_NODE->isSetChildNode()
    }
  }

  override fun equals(other: Any?): Boolean {
    if (other is HelloAll)
        return this.equals(other)
    return false
  }

  fun equals(other: HelloAll?):Boolean {
    if (other == null)
      return false
    if (this == other)
      return true

    val this_present_Variable1: Boolean = true && this.isSetVariable1()
    val other_present_Variable1: Boolean = true && other.isSetVariable1()
    if (this_present_Variable1 || other_present_Variable1) {
      if (!(this_present_Variable1 && other_present_Variable1))
        return false;
      if (!this.Variable1!!.equals(other.Variable1))
        return false;
    }

    val this_present_Variable2: Boolean = true
    val other_present_Variable2: Boolean = true
    if (this_present_Variable2 || other_present_Variable2) {
      if (!(this_present_Variable2 && other_present_Variable2))
        return false;
      if (this.Variable2 != other.Variable2)
        return false;
    }

    val this_present_Variable3: Boolean = true
    val other_present_Variable3: Boolean = true
    if (this_present_Variable3 || other_present_Variable3) {
      if (!(this_present_Variable3 && other_present_Variable3))
        return false;
      if (this.Variable3 != other.Variable3)
        return false;
    }

    val this_present_ChildNode: Boolean = true && this.isSetChildNode()
    val other_present_ChildNode: Boolean = true && other.isSetChildNode()
    if (this_present_ChildNode || other_present_ChildNode) {
      if (!(this_present_ChildNode && other_present_ChildNode))
        return false;
      if (!this.ChildNode!!.equals(other.ChildNode))
        return false;
    }

    return true;
  }

  override fun hashCode():Int {
    var hashCode: Int = 1

    hashCode = hashCode * 8191 + (if(isSetVariable1()) 131071 else 524287)
    if (isSetVariable1())
      hashCode = hashCode * 8191 + Variable1.hashCode()

    hashCode = hashCode * 8191 + Variable2

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(Variable3)

    hashCode = hashCode * 8191 + (if(isSetChildNode()) 131071 else 524287)
    if (isSetChildNode())
      hashCode = hashCode * 8191 + ChildNode.hashCode();

    return hashCode;
  }

  override fun compareTo(other: HelloAll):Int {
    if (!javaClass.equals(other.javaClass)) {
      return javaClass.getName().compareTo(other.javaClass.getName())
    }

    var lastComparison:Int = 0

    lastComparison = java.lang.Boolean.compare(isSetVariable1(), other.isSetVariable1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVariable1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Variable1, other.Variable1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVariable2(), other.isSetVariable2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVariable2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Variable2, other.Variable2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVariable3(), other.isSetVariable3());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVariable3()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Variable3, other.Variable3);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetChildNode(), other.isSetChildNode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChildNode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ChildNode, other.ChildNode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  override fun fieldForId(fieldId: Int):_Fields? {
    return _Fields.findByThriftId(fieldId)
  }

  override fun read(iprot: org.apache.thrift.protocol.TProtocol) {
    scheme<HelloAll>(iprot).read(iprot, this)
  }

  override fun write(oprot: org.apache.thrift.protocol.TProtocol) {
    scheme<HelloAll>(oprot).write(oprot, this)
  }

  override fun toString():String {
    val sb:java.lang.StringBuilder = java.lang.StringBuilder("HelloAll(");
    var first:Boolean = true

    sb.append("Variable1:");
    if (this.Variable1 == null) {
      sb.append("null");
    } else {
      sb.append(this.Variable1);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Variable2:");
    sb.append(this.Variable2);
    first = false;
    if (!first) sb.append(", ");
    sb.append("Variable3:");
    sb.append(this.Variable3);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ChildNode:");
    if (this.ChildNode == null) {
      sb.append("null");
    } else {
      sb.append(this.ChildNode);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  fun validate() {
    // check for required fields
    // check for sub-struct validity
    ChildNode?.validate();
  }

  fun writeObject(out:java.io.ObjectOutputStream) {
    try {
      write(org.apache.thrift.protocol.TCompactProtocol(org.apache.thrift.transport.TIOStreamTransport(out)))
    } catch (te:org.apache.thrift.TException) {
      throw java.io.IOException(te);
    }
  }

  fun readObject(inp:java.io.ObjectInputStream) {
    try {
      // it doesn't seem like you should have to do this, but kotlin serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0
      read(org.apache.thrift.protocol.TCompactProtocol(org.apache.thrift.transport.TIOStreamTransport(inp)))
    } catch (te:org.apache.thrift.TException) {
      throw java.io.IOException(te);
    }
  }

  private class HelloAllStandardSchemeFactory : org.apache.thrift.scheme.SchemeFactory<HelloAllStandardScheme> {
    override fun getScheme():HelloAllStandardScheme {
      return HelloAllStandardScheme()
    }
  }

  private class HelloAllStandardScheme : org.apache.thrift.scheme.StandardScheme<HelloAll>() {

    override fun read(iprot:org.apache.thrift.protocol.TProtocol, struct:HelloAll) {
      lateinit var schemeField: org.apache.thrift.protocol.TField
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin()
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break
        }
        when (schemeField.id.toInt()) {
          1 -> // VARIABLE1
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Variable1 = iprot.readString();
              struct.setVariable1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
          2 -> // VARIABLE2
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.Variable2 = iprot.readI32();
              struct.setVariable2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
          3 -> // VARIABLE3
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.Variable3 = iprot.readI64();
              struct.setVariable3IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
          4 -> // CHILD_NODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.ChildNode = ChildAll();
              struct.ChildNode?.read(iprot);
              struct.setChildNodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
          else ->
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    override fun write(oprot:org.apache.thrift.protocol.TProtocol, struct:HelloAll) {
      struct.validate()

      oprot.writeStructBegin(STRUCT_DESC)
      if (struct.Variable1 != null) {
        oprot.writeFieldBegin(VARIABLE1_FIELD_DESC)
        oprot.writeString(struct.Variable1);
        oprot.writeFieldEnd()
      }
      oprot.writeFieldBegin(VARIABLE2_FIELD_DESC)
      oprot.writeI32(struct.Variable2);
      oprot.writeFieldEnd()
      oprot.writeFieldBegin(VARIABLE3_FIELD_DESC)
      oprot.writeI64(struct.Variable3);
      oprot.writeFieldEnd()
      if (struct.ChildNode != null) {
        oprot.writeFieldBegin(CHILD_NODE_FIELD_DESC)
        struct.ChildNode?.write(oprot);
        oprot.writeFieldEnd()
      }
      oprot.writeFieldStop()
      oprot.writeStructEnd()
    }

  }

  private class HelloAllTupleSchemeFactory : org.apache.thrift.scheme.SchemeFactory<HelloAllTupleScheme> {
    override fun getScheme():HelloAllTupleScheme {
      return HelloAllTupleScheme()
    }
  }

  private class HelloAllTupleScheme : org.apache.thrift.scheme.TupleScheme<HelloAll>() {

    override fun write(oprot:org.apache.thrift.protocol.TProtocol, struct:HelloAll) {
      val prot:org.apache.thrift.protocol.TTupleProtocol = oprot as org.apache.thrift.protocol.TTupleProtocol
      val optionals:java.util.BitSet = java.util.BitSet()
      if (struct.isSetVariable1()) {
        optionals.set(0)
      }
      if (struct.isSetVariable2()) {
        optionals.set(1)
      }
      if (struct.isSetVariable3()) {
        optionals.set(2)
      }
      if (struct.isSetChildNode()) {
        optionals.set(3)
      }
      prot.writeBitSet(optionals, 4)
      if (struct.isSetVariable1()) {
        oprot.writeString(struct.Variable1);
      }
      if (struct.isSetVariable2()) {
        oprot.writeI32(struct.Variable2);
      }
      if (struct.isSetVariable3()) {
        oprot.writeI64(struct.Variable3);
      }
      if (struct.isSetChildNode()) {
        struct.ChildNode?.write(oprot);
      }
    }

    override fun read(iprot: org.apache.thrift.protocol.TProtocol, struct:HelloAll) {
      val prot:org.apache.thrift.protocol.TTupleProtocol = iprot as org.apache.thrift.protocol.TTupleProtocol
      val incoming:java.util.BitSet = prot.readBitSet(4)
      if (incoming.get(0)) {
        struct.Variable1 = iprot.readString();
        struct.setVariable1IsSet(true)
      }
      if (incoming.get(1)) {
        struct.Variable2 = iprot.readI32();
        struct.setVariable2IsSet(true)
      }
      if (incoming.get(2)) {
        struct.Variable3 = iprot.readI64();
        struct.setVariable3IsSet(true)
      }
      if (incoming.get(3)) {
        struct.ChildNode = ChildAll();
        struct.ChildNode?.read(iprot);
        struct.setChildNodeIsSet(true)
      }
    }
  }


  companion object {
    private val STRUCT_DESC: org.apache.thrift.protocol.TStruct = org.apache.thrift.protocol.TStruct("HelloAll");

    private val VARIABLE1_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("Variable1", org.apache.thrift.protocol.TType.STRING, 1.toShort());
    private val VARIABLE2_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("Variable2", org.apache.thrift.protocol.TType.I32, 2.toShort());
    private val VARIABLE3_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("Variable3", org.apache.thrift.protocol.TType.I64, 3.toShort());
    private val CHILD_NODE_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("ChildNode", org.apache.thrift.protocol.TType.STRUCT, 4.toShort());

    private val STANDARD_SCHEME_FACTORY: org.apache.thrift.scheme.SchemeFactory<HelloAllStandardScheme> = HelloAllStandardSchemeFactory()
    private val TUPLE_SCHEME_FACTORY: org.apache.thrift.scheme.SchemeFactory<HelloAllTupleScheme> = HelloAllTupleSchemeFactory()
    // isset id assignments
    private val __VARIABLE2_ISSET_ID: Int = 0
    private val __VARIABLE3_ISSET_ID: Int = 1
    val metaDataMap: Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> = mapOf(
      _Fields.VARIABLE1 to org.apache.thrift.meta_data.FieldMetaData("Variable1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)),
      _Fields.VARIABLE2 to org.apache.thrift.meta_data.FieldMetaData("Variable2", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)),
      _Fields.VARIABLE3 to org.apache.thrift.meta_data.FieldMetaData("Variable3", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)),
      _Fields.CHILD_NODE to org.apache.thrift.meta_data.FieldMetaData("ChildNode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ChildAll::class.java)))
    init {
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HelloAll::class.java, metaDataMap)
    }
    private fun <S : org.apache.thrift.TBase<*, *>> scheme(proto:org.apache.thrift.protocol.TProtocol): org.apache.thrift.scheme.IScheme<S> {
      if(proto.scheme is org.apache.thrift.scheme.StandardScheme<*>) {
        return STANDARD_SCHEME_FACTORY.getScheme() as org.apache.thrift.scheme.IScheme<S>
      }
      return TUPLE_SCHEME_FACTORY.getScheme() as org.apache.thrift.scheme.IScheme<S>
    }
  }
}

