/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.testing.api;

@javax.annotation.processing.Generated(value = ["Autogenerated by Thrift Compiler (0.15.0)"], date = "2021-07-11")
class testOneResponse( 
  private var answer: String? = null // required
): org.apache.thrift.TBase<testOneResponse, testOneResponse.Fields>, java.io.Serializable, Cloneable, Comparable<testOneResponse> {

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  enum class Fields(
    override val thriftFieldId: Short,
    override val fieldName: String
  ) : org.apache.thrift.TFieldIdEnum {
    ANSWER(1, "answer");

    companion object {
      var byName: Map<String, Fields> = mapOf(
        "answer" to ANSWER
      )
      /**
       * Find the Fields constant that matches fieldId, or null if its not found.
       */
      fun findByThriftId(fieldId: Short): Fields? {
        return when(fieldId) {
          (1).toShort() -> // ANSWER
            ANSWER
          else ->
            null
        }
      }

      /**
       * Find the Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      fun findByThriftIdOrThrow(fieldId: Short): Fields {
        return findByThriftId(fieldId)
          ?: throw java.lang.IllegalArgumentException("Field $fieldId doesn't exist!");
      }

      /**
       * Find the Fields constant that matches name, or null if its not found.
       */
      fun findByName(name: String): Fields? {
        return byName.get(name)
      }
    }
  }

    private val metaDataMap: Map<Fields, org.apache.thrift.meta_data.FieldMetaData> = mapOf(
      Fields.ANSWER to org.apache.thrift.meta_data.FieldMetaData("answer", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))
    init {
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(testOneResponse::class.java, metaDataMap)
    }
  /**
   * Performs a deep copy on <i>other</i>.
   */
  constructor(other: testOneResponse) : this() {
    if (other.isSetAnswer()) {
      this.answer = other.answer
    }
  }

  override fun deepCopy(): testOneResponse{
    return testOneResponse(this)
  }

  override fun clear() {
    this.answer = null
  }

  fun getAnswer():String? {
    return this.answer
  }

  fun setAnswer(answer: String?): testOneResponse {
    this.answer = answer
    return this
  }

  fun unsetAnswer() {
    this.answer = null
  }

  /** Returns true if field answer is set (has been assigned a value) and false otherwise */
  fun isSetAnswer(): Boolean {
    return this.answer != null
  }

  fun setAnswerIsSet(value: Boolean) {
    if (!value) {
      this.answer = null
    }
  }

  override fun setFieldValue(field: Fields,  value: Any?) {
      when (field) {
    Fields.ANSWER ->
      if (value == null) {
        unsetAnswer()
      } else {
        setAnswer(value as String)
      }

      }
  }

  override fun getFieldValue(field: Fields): Any? {
    return when(field) {
      Fields.ANSWER -> getAnswer()
    }
  }

  // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
  override fun isSet(field: Fields): Boolean {
    return when (field) {
      Fields.ANSWER->isSetAnswer()
    }
  }

  override fun equals(other: Any?): Boolean {
    if (other is testOneResponse)
        return this.equals(other)
    return false
  }

  fun equals(other: testOneResponse?):Boolean {
    if (other == null)
      return false
    if (this == other)
      return true

    val this_present_answer: Boolean = true && this.isSetAnswer()
    val other_present_answer: Boolean = true && other.isSetAnswer()
    if (this_present_answer || other_present_answer) {
      if (!(this_present_answer && other_present_answer))
        return false;
      if (!this.answer!!.equals(other.answer))
        return false;
    }

    return true;
  }

  override fun hashCode():Int {
    var hashCode: Int = 1

    hashCode = hashCode * 8191 + (if(isSetAnswer()) 131071 else 524287)
    if (isSetAnswer())
      hashCode = hashCode * 8191 + answer.hashCode()

    return hashCode
  }

  override fun compareTo(other: testOneResponse):Int {
    if (!javaClass.equals(other.javaClass)) {
      return javaClass.getName().compareTo(other.javaClass.getName())
    }

    var lastComparison:Int = 0

    lastComparison = java.lang.Boolean.compare(isSetAnswer(), other.isSetAnswer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAnswer()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.answer, other.answer);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  override fun fieldForId(fieldId: Short):Fields? {
    return Fields.findByThriftId(fieldId)
  }

  override suspend fun read(iprot: org.apache.thrift.protocol.TProtocol) {
    scheme<testOneResponse>(iprot).read(iprot, this)
  }

  override suspend fun write(oprot: org.apache.thrift.protocol.TProtocol) {
    scheme<testOneResponse>(oprot).write(oprot, this)
  }

  override fun toString():String {
    val sb:java.lang.StringBuilder = java.lang.StringBuilder("testOneResponse(")
    var first:Boolean = true

    sb.append("answer:")
    if (this.answer == null) {
      sb.append("null")
    } else {
      sb.append(this.answer)
    }
    first = false
    sb.append(")");
    return sb.toString()
  }

  fun validate() {
    // check for required fields
    // check for sub-struct validity
  }

  suspend fun writeObject(out:java.nio.channels.AsynchronousByteChannel) {
    try {
      write(org.apache.thrift.protocol.TCompactProtocol(org.apache.thrift.transport.TIOStreamTransport(out)))
    } catch (te:org.apache.thrift.TException) {
      throw java.io.IOException(te);
    }
  }

  suspend fun readObject(inp:java.nio.channels.AsynchronousByteChannel) {
    try {
      read(org.apache.thrift.protocol.TCompactProtocol(org.apache.thrift.transport.TIOStreamTransport(inp)))
    } catch (te:org.apache.thrift.TException) {
      throw java.io.IOException(te);
    }
  }

  private class testOneResponseStandardSchemeFactory : org.apache.thrift.scheme.SchemeFactory<testOneResponseStandardScheme> {
    override fun getScheme():testOneResponseStandardScheme {
      return testOneResponseStandardScheme()
    }
  }

  private class testOneResponseStandardScheme : org.apache.thrift.scheme.StandardScheme<testOneResponse>() {

    override suspend fun read(iprot:org.apache.thrift.protocol.TProtocol, struct:testOneResponse) {
      lateinit var schemeField: org.apache.thrift.protocol.TField
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin()
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break
        }
        when (schemeField.id.toInt()) {
          1 -> // ANSWER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.answer = iprot.readString()
              struct.setAnswerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
          else ->
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    override suspend fun write(oprot:org.apache.thrift.protocol.TProtocol, struct:testOneResponse) {
      struct.validate()

      oprot.writeStructBegin(STRUCT_DESC)
      if (struct.answer != null) {
        oprot.writeFieldBegin(ANSWER_FIELD_DESC)
        oprot.writeString(struct.answer)
        oprot.writeFieldEnd()
      }
      oprot.writeFieldStop()
      oprot.writeStructEnd()
    }

  }

  private class testOneResponseTupleSchemeFactory : org.apache.thrift.scheme.SchemeFactory<testOneResponseTupleScheme> {
    override fun getScheme():testOneResponseTupleScheme {
      return testOneResponseTupleScheme()
    }
  }

  private class testOneResponseTupleScheme : org.apache.thrift.scheme.TupleScheme<testOneResponse>() {

    override suspend fun write(oprot:org.apache.thrift.protocol.TProtocol, struct:testOneResponse) {
      val prot:org.apache.thrift.protocol.TTupleProtocol = oprot as org.apache.thrift.protocol.TTupleProtocol
      val optionals:java.util.BitSet = java.util.BitSet()
      if (struct.isSetAnswer()) {
        optionals.set(0)
      }
      prot.writeBitSet(optionals, 1)
      if (struct.isSetAnswer()) {
        oprot.writeString(struct.answer)
      }
    }

    override suspend fun read(iprot: org.apache.thrift.protocol.TProtocol, struct:testOneResponse) {
      val prot:org.apache.thrift.protocol.TTupleProtocol = iprot as org.apache.thrift.protocol.TTupleProtocol
      val incoming:java.util.BitSet = prot.readBitSet(1)
      if (incoming.get(0)) {
        struct.answer = iprot.readString()
        struct.setAnswerIsSet(true)
      }
    }
  }


  companion object {
    private val STRUCT_DESC: org.apache.thrift.protocol.TStruct = org.apache.thrift.protocol.TStruct("testOneResponse");

    private val ANSWER_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("answer", org.apache.thrift.protocol.TType.STRING, 1)

    private val STANDARD_SCHEME_FACTORY: org.apache.thrift.scheme.SchemeFactory<testOneResponseStandardScheme> = testOneResponseStandardSchemeFactory()
    private val TUPLE_SCHEME_FACTORY: org.apache.thrift.scheme.SchemeFactory<testOneResponseTupleScheme> = testOneResponseTupleSchemeFactory()
    // isset id assignments
    private fun <S : org.apache.thrift.TBase<S, *>> scheme(proto:org.apache.thrift.protocol.TProtocol): org.apache.thrift.scheme.IScheme<S> {
      if(proto.scheme.isAssignableFrom(org.apache.thrift.scheme.StandardScheme::class.java)) {
        return STANDARD_SCHEME_FACTORY.getScheme() as org.apache.thrift.scheme.IScheme<S>
      }
      return TUPLE_SCHEME_FACTORY.getScheme() as org.apache.thrift.scheme.IScheme<S>
    }
  }
}

