/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.testing.api;

@javax.annotation.processing.Generated(value = ["Autogenerated by Thrift Compiler (0.15.0)"], date = "2021-07-11")
class unsupportedName( 
  private var error: String? = null // required
): org.apache.thrift.TException(),  org.apache.thrift.TBase<unsupportedName, unsupportedName.Fields>, java.io.Serializable, Cloneable, Comparable<unsupportedName> {

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  enum class Fields(
    override val thriftFieldId: Short,
    override val fieldName: String
  ) : org.apache.thrift.TFieldIdEnum {
    ERROR(1, "error");

    companion object {
      var byName: Map<String, Fields> = mapOf(
        "error" to ERROR
      )
      /**
       * Find the Fields constant that matches fieldId, or null if its not found.
       */
      fun findByThriftId(fieldId: Short): Fields? {
        return when(fieldId) {
          (1).toShort() -> // ERROR
            ERROR
          else ->
            null
        }
      }

      /**
       * Find the Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      fun findByThriftIdOrThrow(fieldId: Short): Fields {
        return findByThriftId(fieldId)
          ?: throw java.lang.IllegalArgumentException("Field $fieldId doesn't exist!");
      }

      /**
       * Find the Fields constant that matches name, or null if its not found.
       */
      fun findByName(name: String): Fields? {
        return byName.get(name)
      }
    }
  }

    private val metaDataMap: Map<Fields, org.apache.thrift.meta_data.FieldMetaData> = mapOf(
      Fields.ERROR to org.apache.thrift.meta_data.FieldMetaData("error", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))
    init {
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(unsupportedName::class.java, metaDataMap)
    }
  /**
   * Performs a deep copy on <i>other</i>.
   */
  constructor(other: unsupportedName) : this() {
    if (other.isSetError()) {
      this.error = other.error
    }
  }

  override fun deepCopy(): unsupportedName{
    return unsupportedName(this)
  }

  override fun clear() {
    this.error = null
  }

  fun getError():String? {
    return this.error
  }

  fun setError(error: String?): unsupportedName {
    this.error = error
    return this
  }

  fun unsetError() {
    this.error = null
  }

  /** Returns true if field error is set (has been assigned a value) and false otherwise */
  fun isSetError(): Boolean {
    return this.error != null
  }

  fun setErrorIsSet(value: Boolean) {
    if (!value) {
      this.error = null
    }
  }

  override fun setFieldValue(field: Fields,  value: Any?) {
      when (field) {
    Fields.ERROR ->
      if (value == null) {
        unsetError()
      } else {
        setError(value as String)
      }

      }
  }

  override fun getFieldValue(field: Fields): Any? {
    return when(field) {
      Fields.ERROR -> getError()
    }
  }

  // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
  override fun isSet(field: Fields): Boolean {
    return when (field) {
      Fields.ERROR->isSetError()
    }
  }

  override fun equals(other: Any?): Boolean {
    if (other is unsupportedName)
        return this.equals(other)
    return false
  }

  fun equals(other: unsupportedName?):Boolean {
    if (other == null)
      return false
    if (this == other)
      return true

    val this_present_error: Boolean = true && this.isSetError()
    val other_present_error: Boolean = true && other.isSetError()
    if (this_present_error || other_present_error) {
      if (!(this_present_error && other_present_error))
        return false;
      if (!this.error!!.equals(other.error))
        return false;
    }

    return true;
  }

  override fun hashCode():Int {
    var hashCode: Int = 1

    hashCode = hashCode * 8191 + (if(isSetError()) 131071 else 524287)
    if (isSetError())
      hashCode = hashCode * 8191 + error.hashCode()

    return hashCode
  }

  override fun compareTo(other: unsupportedName):Int {
    if (!javaClass.equals(other.javaClass)) {
      return javaClass.getName().compareTo(other.javaClass.getName())
    }

    var lastComparison:Int = 0

    lastComparison = java.lang.Boolean.compare(isSetError(), other.isSetError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error, other.error);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  override fun fieldForId(fieldId: Short):Fields? {
    return Fields.findByThriftId(fieldId)
  }

  override suspend fun read(iprot: org.apache.thrift.protocol.TProtocol) {
    scheme<unsupportedName>(iprot).read(iprot, this)
  }

  override suspend fun write(oprot: org.apache.thrift.protocol.TProtocol) {
    scheme<unsupportedName>(oprot).write(oprot, this)
  }

  override fun toString():String {
    val sb:java.lang.StringBuilder = java.lang.StringBuilder("unsupportedName(")
    var first:Boolean = true

    sb.append("error:")
    if (this.error == null) {
      sb.append("null")
    } else {
      sb.append(this.error)
    }
    first = false
    sb.append(")");
    return sb.toString()
  }

  fun validate() {
    // check for required fields
    // check for sub-struct validity
  }

  suspend fun writeObject(out:java.nio.channels.AsynchronousByteChannel) {
    try {
      write(org.apache.thrift.protocol.TCompactProtocol(org.apache.thrift.transport.TIOStreamTransport(out)))
    } catch (te:org.apache.thrift.TException) {
      throw java.io.IOException(te);
    }
  }

  suspend fun readObject(inp:java.nio.channels.AsynchronousByteChannel) {
    try {
      read(org.apache.thrift.protocol.TCompactProtocol(org.apache.thrift.transport.TIOStreamTransport(inp)))
    } catch (te:org.apache.thrift.TException) {
      throw java.io.IOException(te);
    }
  }

  private class unsupportedNameStandardSchemeFactory : org.apache.thrift.scheme.SchemeFactory<unsupportedNameStandardScheme> {
    override fun getScheme():unsupportedNameStandardScheme {
      return unsupportedNameStandardScheme()
    }
  }

  private class unsupportedNameStandardScheme : org.apache.thrift.scheme.StandardScheme<unsupportedName>() {

    override suspend fun read(iprot:org.apache.thrift.protocol.TProtocol, struct:unsupportedName) {
      lateinit var schemeField: org.apache.thrift.protocol.TField
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin()
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break
        }
        when (schemeField.id.toInt()) {
          1 -> // ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.error = iprot.readString()
              struct.setErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
          else ->
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    override suspend fun write(oprot:org.apache.thrift.protocol.TProtocol, struct:unsupportedName) {
      struct.validate()

      oprot.writeStructBegin(STRUCT_DESC)
      if (struct.error != null) {
        oprot.writeFieldBegin(ERROR_FIELD_DESC)
        oprot.writeString(struct.error)
        oprot.writeFieldEnd()
      }
      oprot.writeFieldStop()
      oprot.writeStructEnd()
    }

  }

  private class unsupportedNameTupleSchemeFactory : org.apache.thrift.scheme.SchemeFactory<unsupportedNameTupleScheme> {
    override fun getScheme():unsupportedNameTupleScheme {
      return unsupportedNameTupleScheme()
    }
  }

  private class unsupportedNameTupleScheme : org.apache.thrift.scheme.TupleScheme<unsupportedName>() {

    override suspend fun write(oprot:org.apache.thrift.protocol.TProtocol, struct:unsupportedName) {
      val prot:org.apache.thrift.protocol.TTupleProtocol = oprot as org.apache.thrift.protocol.TTupleProtocol
      val optionals:java.util.BitSet = java.util.BitSet()
      if (struct.isSetError()) {
        optionals.set(0)
      }
      prot.writeBitSet(optionals, 1)
      if (struct.isSetError()) {
        oprot.writeString(struct.error)
      }
    }

    override suspend fun read(iprot: org.apache.thrift.protocol.TProtocol, struct:unsupportedName) {
      val prot:org.apache.thrift.protocol.TTupleProtocol = iprot as org.apache.thrift.protocol.TTupleProtocol
      val incoming:java.util.BitSet = prot.readBitSet(1)
      if (incoming.get(0)) {
        struct.error = iprot.readString()
        struct.setErrorIsSet(true)
      }
    }
  }


  companion object {
    private val STRUCT_DESC: org.apache.thrift.protocol.TStruct = org.apache.thrift.protocol.TStruct("unsupportedName");

    private val ERROR_FIELD_DESC: org.apache.thrift.protocol.TField = org.apache.thrift.protocol.TField("error", org.apache.thrift.protocol.TType.STRING, 1)

    private val STANDARD_SCHEME_FACTORY: org.apache.thrift.scheme.SchemeFactory<unsupportedNameStandardScheme> = unsupportedNameStandardSchemeFactory()
    private val TUPLE_SCHEME_FACTORY: org.apache.thrift.scheme.SchemeFactory<unsupportedNameTupleScheme> = unsupportedNameTupleSchemeFactory()
    // isset id assignments
    private fun <S : org.apache.thrift.TBase<S, *>> scheme(proto:org.apache.thrift.protocol.TProtocol): org.apache.thrift.scheme.IScheme<S> {
      if(proto.scheme.isAssignableFrom(org.apache.thrift.scheme.StandardScheme::class.java)) {
        return STANDARD_SCHEME_FACTORY.getScheme() as org.apache.thrift.scheme.IScheme<S>
      }
      return TUPLE_SCHEME_FACTORY.getScheme() as org.apache.thrift.scheme.IScheme<S>
    }
  }
}

